### ISSUE TITLE
Create more than one redirect at a time

### ISSUE THREAD

**Issue by Thor77** [ThomasLeister/webmum#10]
## Case
You want to redirect `postmaster@domain.tld`, `abuse@domain.tld` and `admin@domain.tld` to `youraccount@domain.tld`.
## Now
You have to create 3 Redirects:  

Source | Desination
------------ | -------------
`postmaster@domain.tld` | `youraccount@domain.tld`
`abuse@domain.tld` | `youraccount@domain.tld`
`admin@domain.tld` | `youraccount@domain.tld`

## My desire
You create one Redirect:

Source | Desination
------------ | -------------
`postmaster@domain.tld`  `abuse@domain.tld`  `admin@domain.tld` | `youraccount@domain.tld`  

And the script creates the other entrys itself.

**Comment by ohartl** [comment]
@ThomasLeister in the pull request i am working on i have introduced two new options in the config.

They are totally optional and will just disable the functionality if they are commented out (as the mailbox limit does).

So should those be enabled by default or disabled for compatibility reasons?

```php
...
// Enable multi source redirects, needs a new column in aliase table with VARCHAR(32)
define("DBC_ALIASES_MULTI_SOURCE", "multi_source");	// (Optional, Recommended)


/*
 * General options
 */
// Enable validating that the source addresses are ending with domain from domains
define("VALIDATE_ALIASES_SOURCE_ENABLED", true);		// (Optional, Recommended)
...
```

**Comment by ohartl** [comment]
done with #30
