### ISSUE TITLE
Display error if redirect conflicts with new account

### ISSUE THREAD

**Issue by ThomasLeister** [ThomasLeister/webmum#12]
Display error if redirect conflicts with new account

**Comment by ohartl** [comment]
Can u explain further what you mean, or is it fixed already?

**Comment by ThomasLeister** [comment]
By "redirect" I mean "alias". Let's assume a alias exists, which redirects emails from "myalias@domain.tld" to "me@domain.tld". There should be an error message or warning when the admin tries to create a *mailbox* "myalias@domain.tld", because aliases have higher priorities to postfix than mailboxes. The new mailbox could never be used with the alias existing: No email would ever arrive in the myalias@domain.tld mailbox, but in the "me@domain.tld" mailbox (because of the alias)

**Comment by ohartl** [comment]
ok makes sense, i'll have a look into that too.

**Comment by ThomasLeister** [comment]
Yes, iIagree. What about, a permanent warning on the redirects / alias page and a warning when creating an overriden mailbox?

**Comment by ohartl** [comment]
Sounds nice, maybe the admin should be able to create the redirect then nevertheless, and then mark both the blocking redirect and user in the overview pages with a hint?

**Comment by ThomasLeister** [comment]
I like your idea. Go for it! ;)

**Comment by ohartl** [comment]
@ThomasLeister have a look at 7090bef419f598713d0bc9119b05698f9855619d
