### ISSUE TITLE
Allow multiple admin email addresses

### ISSUE THREAD

**Issue by leo-graf** [ThomasLeister/webmum#15]
It would be really great if multiple admins email addresses could be set.

&thx for this great simple (simply great :) software :)

**Comment by ThomasLeister** [comment]
That should be simple to achieve. If there's some spare time this week I will implement a multi-admin feature. Thanks for your suggestion! :)

**Comment by ThomasLeister** [comment]
Hi Leo, you can now specify multiple admin email addresses in the current version on the master branch. Please note the new configuration syntax.

**Comment by leo-graf** [comment]
Wow, thsi was really fast! Thank you again
