### ISSUE TITLE
webmum wont work with fastcgi

### ISSUE THREAD

**Issue by kecksk0enig** [ThomasLeister/webmum#18]
getting error within apache errorlog.
This is caused by the rewriting magic.
(Whats the use of the rewriting anyway?)
```
[Sun Jan 31 17:50:38.958693 2016] [ssl:debug] [pid 26491] ssl_engine_kernel.c(354): [client 127.0.0.1:38599] AH02034: Subsequent (No.2) HTTPS request received for child 0 (server webmum.MYURL.TLD:443)
[Sun Jan 31 17:50:38.958940 2016] [authz_core:debug] [pid 26491] mod_authz_core.c(809): [client 127.0.0.1:38599] AH01626: authorization result of Require all granted: granted
[Sun Jan 31 17:50:38.958961 2016] [authz_core:debug] [pid 26491] mod_authz_core.c(809): [client 127.0.0.1:38599] AH01626: authorization result of <RequireAny>: granted
[Sun Jan 31 17:50:38.960175 2016] [core:error] [pid 26491] [client 127.0.0.1:38599] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun Jan 31 17:50:38.960192 2016] [core:debug] [pid 26491] core.c(3613): [client 127.0.0.1:38599] AH00121: r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960204 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960215 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960224 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960233 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960242 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960251 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960260 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960268 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/php5-fcgi/
[Sun Jan 31 17:50:38.960277 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /php5-fcgi/
[Sun Jan 31 17:50:38.960285 2016] [core:debug] [pid 26491] core.c(3620): [client 127.0.0.1:38599] AH00122: redirected from r->uri = /
```

**Comment by lastsamurai26** [comment]
i work with fcgi and the tools is working :)

**Comment by ThomasLeister** [comment]
@kecksk0enig URL rewriting is used for nicer URLs. As webmum works on @lastsamurai26 s fcgi instance I suggest to re-check your webserver configuration. Maybe you two can compare your configurations if you are both using apache.

**Comment by kecksk0enig** [comment]
@lastsamurai26 would you mind to shhare your config?
mine:
```
<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin webmaster@MYURL.TLD
		ServerName webmum.MYURL.TLD

                DocumentRoot /var/www/MYURL.TLD/webmum
		LogLevel DEBUG
                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined
 
                SSLEngine on

                SSLCertificateFile      /etc/letsencrypt/live/MYURL.TLD/cert.pem       
                SSLCertificateKeyFile /etc/letsencrypt/live/MYURL.TLD/privkey.pem
                SSLCertificateChainFile /etc/letsencrypt/live/MYURL.TLD/chain.pem


		RewriteEngine on
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteRule (.*)\.css$ $1.css [L]
		RewriteRule ^(.*)$ /index.php [L,QSA]
        </VirtualHost>
</IfModule>
```
/etc/apache2/mods-enabled/fastcgi.conf:
```
<IfModule mod_fastcgi.c>
 AddType application/x-httpd-fastphp5 .php
 Action application/x-httpd-fastphp5 /php5-fcgi
 Alias /php5-fcgi /usr/lib/cgi-bin/php5-fcgi
 FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi -socket /var/run/php5-fpm.sock -pass-header Authorization
 <Directory /usr/lib/cgi-bin>
  Require all granted
 </Directory>
</IfModule>

```

**Comment by lastsamurai26** [comment]
/etc/httpcf/mods-available/fcgi.conf 

`<IfModule mod_fcgid.c>
 AddHandler    fcgid-script .fcgi
  # 20MB should be enough
 MaxRequestLen 20000000
 FcgidIdleTimeout 360
 FcgidProcessLifeTime 3600
 FcgidMaxProcesses 30
 FcgidMaxProcessesPerClass 20
 FcgidMinProcessesPerClass 1
 FcgidConnectTimeout 60
 FcgidIOTimeout 90
 FcgidInitialEnv RAILS_ENV production
 FcgidIdleScanInterval 10
 FcgidErrorScanInterval 5
 FcgidZombieScanInterval 5


  <IfModule mod_mime.c>
   AddHandler fcgid-script .fcgi
 </IfModule>

</IfModule>
`

this is my sites (like myurl.tld.conf)

`<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin admin@dunkleallianz.net
                ServerName myurl.tld
                ServerAlias www.myurl.tld
                ServerAlias www.my-url.tld
                ServerAlias my.url.tld
                SuexecUserGroup myurl.tld myurl.tld
                AddHandler fcgid-script .php
                DocumentRoot "/var/www/vhosts/myurl.tld/docs"
                DirectoryIndex index.htm index.html index.php
                RewriteEngine on
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^\/mum/(.*)\.css$ /mum/$1.css [L]
                RewriteRule ^\/mum/(.*)$ /mum/index.php [L,QSA]


                SSLEngine on

                SSLCertificateFile      /etc/ssl/certs/myurl.tld.pem
                SSLCertificateKeyFile /etc/ssl/private/myurl.tld.key

                #SSLCertificateChainFile /etc/httpcf/ssl.crt/server-ca.crt


                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                <Directory />
                   Options FollowSymLinks
                   AllowOverride None
                </Directory>

                <Directory "/var/www/vhosts/myurl.tld/docs">
                   Options -Indexes +MultiViews +FollowSymLinks +ExecCGI
                   FCGIWrapper /var/www/vhosts/myurl.tld/php-fcgi/php-fcgi-starter .php
                   Order allow,deny
                   allow from all
                   AllowOverride all
                </Directory>


                BrowserMatch "MSIE [2-6]" \
                                nokeepalive ssl-unclean-shutdown \
                                downgrade-1.0 force-response-1.0
                 BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
               ErrorLog /var/www/vhosts/myurl.tld/logs/error.log
               LogLevel warn
               CustomLog /var/www/vhosts/myurl.tld/logs/access.log combined
               ServerSignature On

        </VirtualHost>
</IfModule>
`


I use the WebMUM in a subfolder of my maindomain

i using on my own Compiled  apache 2.4, php 7, mariadb and fcgi not factcgi

**Comment by kecksk0enig** [comment]
Hi got it working....

new reqrite rules: 
```
RewriteEngine on
RewriteCond %{REQUEST_URI} ^/php5-fcgi/(.*)
RewriteRule . - [L]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule (.*)\.css$ $1.css [L]
RewriteRule ^(.*)$ /index.php [L,QSA]
```

so the first Rewrite Condition kid of breaks the infinite loop and everything is okay.
(the path php5-fcgi may be system dependent and is retrievd from the debug log)
