### ISSUE TITLE
 Cannot modify header information 

### ISSUE THREAD

**Issue by lastsamurai26** [ThomasLeister/webmum#19]
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/xxxxxx/docs/mum/include/php/template/header.php:5) in /var/www/vhosts/xxxxxx/docs/mum/include/php/pages/start.php on line 3

Notice: Undefined variable: quota in /var/www/vhosts/xxxxxx/docs/mum/include/php/pages/admin/edituser.php on line 75

Woran kann dies liegen bei uns läuft php 7 auf Fcgi basis

**Comment by ohartl** [comment]
May be fixes with #20 and #26 if its pulled. Can you test it again then?

**Comment by lastsamurai26** [comment]
sry with the news master the problem is the same

Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/xxx.de/docs/mum/include/php/template/header.php:5) in /var/www/vhosts/xxx.de/docs/mum/include/php/global.inc.php on line 140

**Comment by ohartl** [comment]
Can you please describe when that warning appears, The Url, action you are trying to do do?

It sounds like a problem with redirection, this is common when some output was already generate before sending the location header to redirect..

**Comment by lastsamurai26** [comment]
I can ..

After the Login 
um/include/php/template/header.php:5) in /var/www/vhosts/xxx.de/docs/mum/include/php/global.inc.php on line 140

Create a User 
/mum/include/php/template/header.php:5) in /var/www/vhosts/xxxx.de/docs/mum/include/php/global.inc.php on line 140

create a Domain
mum/include/php/template/header.php:5) in /var/www/vhosts/xxxx.de/docs/mum/include/php/global.inc.php on line 140

Create a Redirect
There was an error running the query [Column count doesn't match value count at row 1]


and the Same on delete :)

i use php 7 with fcgid on apache 2.4

**Comment by ohartl** [comment]
and what commit are you running the current? 
just want to make sure that you ran `git pull` and pulled this repo, not your own fork (because that is outdated)

**Comment by ThomasLeister** [comment]
... and make sure you pull / clone from "dev" branch since it contains the latest code version. (I've introduced the new dev branch yesterday)

**Comment by lastsamurai26** [comment]
So i have test the Dev branch and with this branch i have the following errors

```
Notice: Undefined index: DOCUMENT_URI in /var/www/vhosts/xx.de/docs/mum/index.php on line 30

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/vhosts/xx.de/docs/mum/index.php:30) in /var/www/vhosts/xx.de/docs/mum/include/php/default.inc.php on line 3

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/vhosts/xxx.de/docs/mum/index.php:30) in /var/www/vhosts/xxx.de/docs/mum/include/php/default.inc.php on line 3

Warning: session_regenerate_id(): Cannot regenerate session id - headers already sent in /var/www/vhosts/xxx.de/docs/mum/include/php/default.inc.php on line 4
```

this is the config 

```
<?php

/*  DO NOT EDIT THIS FILE!
    Instead, copy this config file to config.inc.php and make your changes
    in the copied version. This is just a template!
*/



/*
 * MySQL server and database settings
 */

define("MYSQL_HOST", "localhost");
define("MYSQL_USER", "xxxx");
define("MYSQL_PASSWORD", "xxxx");
define("MYSQL_DATABASE", "xxxx");


/*
 * Database table names
 */

// Table names
define("DBT_USERS", "users");
define("DBT_DOMAINS", "domains");
define("DBT_ALIASES", "aliases");

// Users table columns
define("DBC_USERS_ID", "id");
define("DBC_USERS_USERNAME", "username");
define("DBC_USERS_DOMAIN", "domain");
define("DBC_USERS_PASSWORD", "password");
define("DBC_USERS_MAILBOXLIMIT", "mailbox_limit");		// (Optional)

// Domains table columns
define("DBC_DOMAINS_ID", "id");
define("DBC_DOMAINS_DOMAIN", "domain");

// Aliases table columns
define("DBC_ALIASES_ID", "id");
define("DBC_ALIASES_SOURCE", "source");
define("DBC_ALIASES_DESTINATION", "destination");
// Enable multi source redirects, needs a new column in aliase table with VARCHAR(32)
//define("DBC_ALIASES_MULTI_SOURCE", "multi_source");	// (Optional, Recommended)


/*
 * General options
 */
// Enable validating that the source addresses are ending with domain from domains
//define("VALIDATE_ALIASES_SOURCE_DOMAIN_ENABLED", true);	// (Optional, Recommended)


/*
 * Frontend paths
 */

define("FRONTEND_BASE_PATH", "https://xxx.de/mum/");
define("SUBDIR", "mum/");


/*
 * Admin e-mail address
 */

// outdated: define("ADMIN_EMAIL", "admin@domain.tld");
// new: $admins = array("admin1@server.tld", "admin2@server.tld");
$admins = array("xxx@xxx.de");



/*
 * Password
 */
 /*
 * Select on of the following schemas (only these are supported)
 * SHA-512, SHA-256, BLOWFISH
 */
define("PASS_HASH_SCHEMA", "SHA-512");

//minimum password length
define("MIN_PASS_LENGTH", 8);

/*
 * Write log file? Failed login attempts will be written to the logfile.
 * You can mointor the logfile with fail2ban and ban attackers' IP-addresses.
 * Make sure that PHP has permission to create the log directory and webmum.log (write permissions for php user)
 *
 * Default: Do not write logfile
 */

// define("WRITE_LOG", true);
// define("WRITE_LOG_PATH","/var/www/webmum/log/");


/*
 * Frontend options
 */

// Separator for email lists
define("FRONTEND_EMAIL_SEPARATOR_TEXT", ', '); // possible values: ', ' (default), '; ', PHP_EOL (newline)
define("FRONTEND_EMAIL_SEPARATOR_FORM", ','); // possible values: ',' (default), ';', PHP_EOL (newline)


?>
```

**Comment by ohartl** [comment]
Thanks a lot @lastsamurai26 for reporting the bug an being so patient, since the session was not started at the very beginning of a request, some notice messages etc. messed up the start of the session.
Sessions cannot be started when data is written to output stream already, because headers are already send then.

Done with 2a62fcb377c0a3b939bd7841be1b8e641be1b88b

**Comment by lastsamurai26** [comment]
i don't know whats wrong but the error is the same ;/ after reupload the webmum.

Create a User 
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/xxxx.de/httpdocs/mum/include/php/template/header.php:5) in /var/www/vhosts/xxxx.de/httpdocs/mum/include/php/global.inc.php on line 91

the same by Delte user, create domain, delete Domain and so on

**Comment by ohartl** [comment]
@lastsamurai26 try out c4fa44cff5a52db4e1c564c7f21f9eea5ff6e87c please, hope it finally fixes it for everybody.

**Comment by lastsamurai26** [comment]
It works 

but i have one problem after the Logout 

after the Logout i'm landing here 
https://xxxx.de/mum//

if this a problem in the config, if yes how can i fix this 


```
/*
 * Frontend paths
 */

define("FRONTEND_BASE_PATH", "https://xxx.de/mum/");
define("SUBDIR", "mum/");
```

I think the subdir is wrong ?!

**Comment by ohartl** [comment]
Thanks for reporting, both fixed. You got it right with urls.

Please open another issue with next thing you find please, otherwise its hard to keep track.
