### ISSUE TITLE
Disable autocompletion on non login forms

### ISSUE THREAD

**Issue by ohartl** [ThomasLeister/webmum#24]
This would be helpfull since for example edit fields wouldnt be autofilled by the browser.
For example in the edituser page when the username is recognized by the browser-autocomplete it fill prefill the password field.

In general password fields should not be prefilled or prefillable on registration and password edit pages.

**Comment by ThomasLeister** [comment]
I would appreciate if you submitted a pull request fixing that. ;) ... should be some additional HTML attributes on some formular elements.

**Comment by ohartl** [comment]
is also in #37
