### ISSUE TITLE
Add possibility to restrict domains for admin users

### ISSUE THREAD

**Issue by leo-graf** [ThomasLeister/webmum#28]
I started to share my server with an ngo and i would really appreciate this functionallity. It's a share-of-trust but who knows :)

My php skills are limited so i would try to contribute in another way..

**Comment by ohartl** [comment]
Should a limited admin be able to delete domains he is limited to?
Or can he just not access domains at all, but users and redirects?

**Comment by ohartl** [comment]
done with dda397074c39eccca26fe02c95a16ebb3d312f91

**Comment by leo-graf** [comment]
This is exactly what I needed and it got through all the testing i did. Thank you very much! I don't have any more ideas at the moment but I'll have it in my mind when i start theming...
