### ISSUE TITLE
Defining new aliases not possible

### ISSUE THREAD

**Issue by dadosch** [ThomasLeister/webmum#32]
Defining a new aliases with webmum is not possible (for me).

` There was an error running the query [Column count doesn't match value count at row 1]`

But if I define one directly via mysql it is shown in the webpage.

I'm not sure, where the problem lies.

**Comment by dadosch** [comment]
Only editing existing entries works fine.

**Comment by ThomasLeister** [comment]
I can confirm this problem and will have a look at it. Thx for your report!

**Comment by ThomasLeister** [comment]
The SQL query on creation is:

```
INSERT INTO `aliases` (`source`, `destination` ) VALUES ('fgh@trashserver.net', 'gfh@trashserver.net', NULL);
```

... which of course cannot work. Maybe @ohartl can fix this?

**Comment by ohartl** [comment]
Ups, i will fix it.
