### ISSUE TITLE
Links in WebMUM referring to the project leave trails

### ISSUE THREAD

**Issue by ohartl** [ThomasLeister/webmum#33]
Under https://github.com/ThomasLeister/webmum/graphs/traffic everybody can see some urls to WebMUM installs, thats not good. If a security vulnerability is found by someone, he can directly visit some installs.

One solution would be to use an url shortener without stats for those urls, any other idea tough?

**Comment by ThomasLeister** [comment]
What about using https://git.io/ ?

**Comment by ohartl** [comment]
Why not use the github shortner, can you change it?

**Comment by ThomasLeister** [comment]
Done https://github.com/ThomasLeister/webmum/commit/8954a01b69c8d439cea9ea6c540469feb3a7efce
