### ISSUE TITLE
Password does not saved

### ISSUE THREAD

**Issue by lastsamurai26** [ThomasLeister/webmum#36]
Hey, 

The password is not saved to the database.

The Problem is when you create a User, change password myself or
Change Password from a other user.

if you create a User the password variable is empty so the database column "password" is empty
If you change the Password in the Manage User site, then the password does not change 
if you change the password over the Personal changes so then your own Password was changed

**Comment by ohartl** [comment]
Can you test 0b1c3788abccf04ffaca75180b1a998ea678f02a ?

**Comment by lastsamurai26** [comment]
:) i can and it works 

thx :D

**Comment by ohartl** [comment]
well thanks for reporting ;)
