### ISSUE TITLE
Login page issue

### ISSUE THREAD

**Issue by dadosch** [ThomasLeister/webmum#40]
after login, a blank page is shown. only after a page reload
```
[Admin Dashboard]
[Personal Dashboard]
```

are shown.

I'm not sure, but I think the problem lies in  webmum/include/php/pages/login.php at line 14

**Comment by ohartl** [comment]
Can u maybe give more details? Are you using the current dev version or an older version? Can you post the error log entry referencing to that problem?
Line 14 of the current version just calls the login method of the authentication.

**Comment by dadosch** [comment]
I'm using the master branch. all files are up to date. I enabled logs in the config but there isn't a config file...

I'm going to check this later this week.

**Comment by ohartl** [comment]
Ok there may be an unknown error in the master branch, with error log i mean the php error log, not the logging from webmum.

And what does that sentence mean 
> I enabled logs in the config but there isn't a config file...
 i don't get it, sorry.

Can you try out the dev branch, configure it as explained in the README, and check if the problem still exists too?

**Comment by ohartl** [comment]
@dadosch just wanted to remind please read the last comment and see if it helps you

**Comment by dadosch** [comment]
***** ITS WORKING NOW *****
First I stuck on the alert that it couldnt connect do the database, but I named the config `config.inc.php` like in previous versions. now with `config.php` everything works fine.

//close
