### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Uigedail** [ThomasLeister/webmum#46]
I have installed webmin as described and i have copied the config file and delete to sample file.
But the page shows me the same message.

<?php

/**
 * Loading system
 */
require_once 'include/php/default.inc.php';

/**
 * Handle request
 */
$content = Router::executeCurrentRequest();

if(defined('USING_OLD_CONFIG')){
	$content = '<div class="notification notification-fail"><strong>Your WebMUM installation is still using the old deprecated config style!</strong><br><br>Please update your config to the new style (an example config can be found in <cite>config.php.example</cite>)<br>and delete your old <cite>config.inc.php</cite> and <cite>config.inc.php.example</cite>.</div>'.$content;
}

echo Router::loadAndBufferOutput(
	'include/php/template/layout.php',
	array(
		'content' => $content,
	)
);

I have no idea what i have to change to use webmum

**Comment by ohartl** [comment]
Well this is easy, looks like your webserver is not telling php to process the .php file, so the code of the index.php was returned, not the result. Please go ahead and configure your webserver and php combination correctly and it should be fine :)
