### ISSUE TITLE
Admin domain limits doesn't work

### ISSUE THREAD

**Issue by alrol** [ThomasLeister/webmum#47]
Hello ohartl,

first of all: Thanks for developing and helping! It is an great tool! Thanks!

Today i installed the actual Branch of webmum via "git clone https://github.com/ThomasLeister/webmum".  I had an working install, but i would the newer version of webmum and a easy way to update, so i moved the old install from .../webmum to .../webmum-old and installed the new version. 

Then i copied the config.php.example to config.php and edit the config-file. In the "options" section i enabled the
 `'enable_admin_domain_limits' => true,` 
and i added an Domainadmin:
`'admin_domain_limits' => array(`
`'admin@domain.tld' => array('domain.tld'),`
`),`
then i restart the apache and look. But it doesn't work. Must i change any entry in the users table at the database? I upgraded an existing user to Domain-Admin.

**Comment by ohartl** [comment]
Did you also add the new Domain-Admin to the 'admins' array?

**Comment by alrol** [comment]
Thanks, it work's.

I didn't the Admin in the 'admins' array?
